option(TOO_DEPLOYMENT_BUILD "do a final release build for deployment" $ENV{DeployArtifacts})
set(TOO_DEPLOY_TARGET "" CACHE STRING "Special deployment choice (if OS is not sufficient) out of: uwp, win_desk_bridge, linuxAppDir")

if ("${TOO_DEPLOY_TARGET}" STREQUAL "win_desk_bridge")
    add_definitions(-DTOO_DEPLOY_TO_WIN_DESK_BRIDGE)
    add_definitions(-DTOO_DEPLOY_TO_WINSTORE)
elseif ("${TOO_DEPLOY_TARGET}" STREQUAL "uwp")
    add_definitions(-DTOO_DEPLOY_TO_UWP)
    add_definitions(-DTOO_DEPLOY_TO_WINSTORE)
#elseif ("${TOO_DEPLOY_TARGET}" STREQUAL "steam")
#    add_definitions(-DTOO_DEPLOY_TO_STEAM)
endif ()
