# taken from qt-android-cmake, in case we don't use that but still need to find boost e.g.
macro(find_host_package)
    set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
    set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY NEVER)
    set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE NEVER)
    set(WIN32_backup ${WIN32})
    set(UNIX_backup ${UNIX})
    set(APPLE_backup ${APPLE})
    if (CMAKE_HOST_WIN32)
        set(WIN32 1)
        set(UNIX)
    elseif (CMAKE_HOST_APPLE)
        set(APPLE 1)
        set(UNIX)
    endif ()
    find_package(${ARGN})
    set(WIN32 ${WIN32_backup})
    set(APPLE ${UNIX_backup})
    set(UNIX ${APPLE_backup})
    set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM ONLY)
    set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
    set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
endmacro()
