set(enable-lgpl ON CACHE BOOL "" FORCE)
set(enable-octave-install OFF CACHE BOOL "" FORCE)
set(enable-png OFF CACHE BOOL "" FORCE)
set(enable-pthr-widget OFF CACHE BOOL "" FORCE)
set(enable-zlib OFF CACHE BOOL "" FORCE)
if ("${TOO_DEPLOY_TARGET}" STREQUAL "uwp" OR TOO_ANDROID)
    set(enable-opengl OFF CACHE BOOL "" FORCE)
endif ()
if ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "Clang")
    set(enable-openmp OFF CACHE BOOL "" FORCE)
    set(MGL_HAVE_C99_COMPLEX OFF CACHE BOOL "" FORCE)
endif ()
if (TOO_MACOS)
    set(enable-openmp OFF CACHE BOOL "" FORCE)
    set(enable-pthread ON CACHE BOOL "" FORCE)
endif()
