// 2011-20

//! \file Most common and basic preprocessor defines.

// no include guard intentionally

// Impl. note: you can't undef those that are used in definitions of other macros themselves, the most fundamental
// ones, so to say.
#undef UL_OS_WINDOWS
#undef UL_OS_WINDOWS_64
#undef UL_OS_WINDOWS_DESKTOP_GE_WIN81
#undef UL_OS_WINDOWS_DESKTOP
#undef UL_OS_WINDOWS_UWP_APP
#undef UL_OS_WINDOWS_UWP_DESKTOP_APP
#undef UL_OS_WINDOWS_UWP_PHONE_APP
#undef UL_OS_WINDOWS_DESKTOP_LT_WIN81
#undef UL_OS_WINDOWS_DESKTOP
#undef UL_OS_UNIX
#undef UL_OS_LINUX
#undef UL_OS_MAC
#undef UL_OS_MAC
#undef UL_OS_MSDOS
#undef UL_OS_WINDOWS_CE
#undef UL_OS_FREEBSD
#undef UL_OS_UNIX
#undef UL_OS_ANDROID
#undef UL_COMP_MS_VISUAL_STUDIO_CPP
#undef UL_COMP_MS_VS_VER
#undef UL_COMP_BORLAND_CPP
#undef UL_COMP_CLANG
#undef UL_COMP_CLANG_VER
#undef UL_COMP_GNU_CPP
#undef GCC_VERSION
#undef UL_COMP_GNU_CPP_VER
#undef UL_COMP_MINGW
#undef UL_COMP_MINGW_VER
#undef UL_COMP_CYGWIN
#undef UL_COMP_INTEL
#undef UL_STDLIB_MSVC
#undef UL_STDLIB_GNU_LIBSTDCPP
#undef UL_STDLIB_CLANG_LIBCPP
#undef UL_LANG_STANDARD_C
#undef UL_LANG_STANDARD_C89
#undef UL_LANG_STANDARD_C99
#undef UL_LANG_STANDARD_CPP
#undef UL_LANG_STANDARD_CPP_CLI
#undef UL_LANG_STANDARD_CPP_CLI04
#undef UL_LANG_STANDARD_EMBCPP
//#undef UL_DEBUG
#undef UL_HAS_NO_CPP11_U8
#undef UL_HAS_CPP11_DEFAULT_MOVES
#undef UL_HAS_NO_CPP11_CONSTEXPR
#undef UL_HAS_NO_CPP11_NOEXCEPT
#undef UL_HAS_NO_CPP14_TYPE_TRAITS_T_SHORTCUTS
#undef UL_HAS_NO_ACCUMULATE_ALG
#undef UL_HAS_NO_CPP14_MAKE_UNIQUE
#undef UL_HAS_NO_CODECVT
#undef UL_HAS_NO_CONSTEXPR_STD_RATIO
#undef UL_SIZEOF_WCHAR_T
#undef UL_HAS_BRACE_INIT_MEMBER_NON_STATIC
#undef UL_HAS_COMPILER_WARNING_INHERITS_BY_DOMINANCE
#undef UL_CAN_BUILD_WINRT_WRL_UWP
//#undef UL_STRINGIFY_VALUE
//#undef UL_STRINGIFY
//#undef UL_CONCAT_2
//#undef UL_CONCAT_VALUES_2
#undef UL_CONCAT_3
#undef UL_CONCAT_VALUES_3
//#undef UL_ANONYMOUS_IDENTIFIER_IMPL
//#undef UL_ANONYMOUS_IDENTIFIER
//#undef UL_DUMMY
//#undef UL_PRAGMA_STR
//#undef UL_PRAGMA
//#undef UL_NOOP
//#undef UL_DEPRECATED
