/**
\file
All-in-one include file for this part of the lib.
*/

#ifndef BASICCODESUPPORT_H_TRHOG4589HG3589HG
#define BASICCODESUPPORT_H_TRHOG4589HG3589HG

#include "algebra.hpp"
#include "almost_equal.hpp"
#include "any.hpp"
#include "array.hpp"
#include "assert.hpp"
#include "bits.hpp"
#include "c_array.hpp"
#include "concepts.hpp"
#include "crash.hpp"
#include "debug.hpp"
#include "enum_bitset.hpp"
#include "enum_cast.hpp"
#include "error.hpp"
#include "file.hpp"
#include "finally.hpp"
#include "floating_point.hpp"
#include "format_number.hpp"
#include "foundations.hpp"
#include "hash.hpp"
#include "ignore_unused.hpp"
#include "integer.hpp"
#include "map.hpp"
#include "math.hpp"
#include "matrix.hpp"
#include "narrow.hpp"
#include "number.hpp"
#include "operation.hpp"
#include "overflow.hpp"
#include "profiler.hpp"
#include "ptr.hpp"
#include "ptr2ref.hpp"
#include "random.hpp"
#include "ratio.hpp"
#include "round.hpp"
#include "shared_instance.hpp"
#include "sizeof.hpp"
#include "three_way_compare.hpp"
#include "trace.hpp"
#include "transformation.hpp"
#include "type_name.hpp"
#include "xor.hpp"
#include "std/array.hpp"
#include "std/circular_buffer.hpp"
#include "std/exception.hpp"
#include "std/integer_sequence.hpp"
#include "std/std_ext_filesystem.hpp"
#include "std/std_extensions.hpp"
#include "std/vector.hpp"
#include "thread/atomic.hpp"
#include "thread/hw.hpp"
#include "thread/pin.hpp"
#include "thread/waitcircbuffer.hpp"
#include "thread/waitqueue.hpp"
#include "type/listener.hpp"
#include "type/non_copyable.hpp"
#include "type/on_before_destroy.hpp"
#include "type/on_before_destroy_notifier.hpp"
#include "type/standaloneop.hpp"

#include "mb/ul/buildenv/config.hpp"

UL_HEADER_END

#endif
