// Markus Borris, 2011-20
// This file is part of tfl library.

//!
/** Most common and basic preprocessor defines.*/
//! \file

// no include guard intentionally

// Impl. note: you can't undef those that are used in definitions of other macros themselves, the most fundamental
// ones, so to say.
#undef TOO_OS_WINDOWS
#undef TOO_OS_WINDOWS_64
#undef TOO_OS_WINDOWS_DESKTOP_GE_WIN81
#undef TOO_OS_WINDOWS_DESKTOP
#undef TOO_OS_WINDOWS_UWP_APP
#undef TOO_OS_WINDOWS_UWP_DESKTOP_APP
#undef TOO_OS_WINDOWS_UWP_PHONE_APP
#undef TOO_OS_WINDOWS_DESKTOP_LT_WIN81
#undef TOO_OS_WINDOWS_DESKTOP
#undef TOO_OS_UNIX
#undef TOO_OS_LINUX
#undef TOO_OS_MAC
#undef TOO_OS_MAC
#undef TOO_OS_MSDOS
#undef TOO_OS_WINDOWS_CE
#undef TOO_OS_FREEBSD
#undef TOO_OS_UNIX
#undef TOO_OS_ANDROID
#undef TOO_COMP_MS_VISUAL_STUDIO_CPP
#undef TOO_COMP_MS_VS_VER
#undef TOO_COMP_BORLAND_CPP
#undef TOO_COMP_CLANG
#undef TOO_COMP_CLANG_VER
#undef TOO_COMP_GNU_CPP
#undef GCC_VERSION
#undef TOO_COMP_GNU_CPP_VER
#undef TOO_COMP_MINGW
#undef TOO_COMP_MINGW_VER
#undef TOO_COMP_CYGWIN
#undef TOO_COMP_INTEL
#undef TOO_STDLIB_MSVC
#undef TOO_STDLIB_GNU_LIBSTDCPP
#undef TOO_STDLIB_CLANG_LIBCPP
#undef TOO_LANG_STANDARD_C
#undef TOO_LANG_STANDARD_C89
#undef TOO_LANG_STANDARD_C99
#undef TOO_LANG_STANDARD_CPP
#undef TOO_LANG_STANDARD_CPP_CLI
#undef TOO_LANG_STANDARD_CPP_CLI04
#undef TOO_LANG_STANDARD_EMBCPP
//#undef TOO_DEBUG
#undef TOO_HAS_NO_CPP11_U8
#undef TOO_HAS_CPP11_DEFAULT_MOVES
#undef TOO_HAS_NO_CPP11_CONSTEXPR
#undef TOO_HAS_NO_CPP11_NOEXCEPT
#undef TOO_HAS_NO_CPP14_TYPE_TRAITS_T_SHORTCUTS
#undef TOO_HAS_NO_ACCUMULATE_ALG
#undef TOO_HAS_NO_CPP14_MAKE_UNIQUE
#undef TOO_HAS_NO_CODECVT
#undef TOO_HAS_NO_CONSTEXPR_STD_RATIO
#undef TOO_SIZEOF_WCHAR_T
#undef TOO_HAS_BRACE_INIT_MEMBER_NON_STATIC
#undef TOO_HAS_COMPILER_WARNING_INHERITS_BY_DOMINANCE
#undef TOO_CAN_BUILD_WINRT_WRL_UWP
//#undef TOO_STRINGIFY_VALUE
//#undef TOO_STRINGIFY
#undef TOO_CONCAT_2
#undef TOO_CONCAT_VALUES_2
#undef TOO_CONCAT_3
#undef TOO_CONCAT_VALUES_3
#undef TOO_ANONYMOUS_IDENTIFIER_IMPL
//#undef TOO_ANONYMOUS_IDENTIFIER
//#undef TOO_DUMMY
//#undef TOO_PRAGMA_STR
//#undef TOO_PRAGMA
//#undef TOO_NOOP
//#undef TOO_DEPRECATED
