name: continuous integration tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  preset-test:
    uses: devmarkusb/gh-workflows/.github/workflows/preset-test.yml@main
    with:
      matrix_config: >
        [
          {"preset": "clang-libc++-maxwarn-release", "image": "ghcr.io/bemanproject/infra-containers-clang:latest"},
          {"preset": "clang-libc++-allwarn-release", "image": "ghcr.io/bemanproject/infra-containers-clang:latest"}
        ]
