name: codecov

on: push

jobs:
  cov:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.7
    - name: Generate coverage report
      run: |
        pip install pytest
        pip install pytest-cov
        pytest --cov=./ --cov-report=xml
    - uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)
