name: iwyu

on: push

jobs:
  build:
    strategy:
      matrix:
        build_type: [Debug]
        config:
          - {os: ubuntu-latest,  compiler: LLVM, CC: clang, CXX: clang++}

    env:
      CC: ${{matrix.config.CC}}
      CXX: ${{matrix.config.CXX}}

    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ${{matrix.config.os}}

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}}

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}

    - name: Run Include What You Use
      uses: EmilGedda/include-what-you-use-action@v1
      with:
        compilation-database-path: '${{github.workspace}}/build'
        output-format: 'iwyu' # Or 'clang'
        no-error: 'true'

