option(DEPLOYMENT_BUILD "do a final release build for deployment" $ENV{DeployArtifacts})
set(DEPLOY_TARGET "" CACHE STRING "Special deployment choice (if OS is not sufficient) out of: winstore, ... or download (default, also if left empty)")

if (DEPLOY_TARGET STREQUAL "win_desk_bridge")
    add_definitions(-DTOO_DEPLOY_TO_WIN_DESK_BRIDGE)
    add_definitions(-DTOO_DEPLOY_TO_WINSTORE)
elseif (DEPLOY_TARGET STREQUAL "uwp")
    add_definitions(-DTOO_DEPLOY_TO_UWP)
    add_definitions(-DTOO_DEPLOY_TO_WINSTORE)
    set(TOO_BUILD_UNITTESTS OFF CACHE BOOL "do not change for uwp" FORCE)
#elseif (DEPLOY_TARGET STREQUAL "steam")
#    add_definitions(-DTOO_DEPLOY_TO_STEAM)
endif ()

if (ANDROID)
    set(TOO_BUILD_UNITTESTS OFF CACHE BOOL "do not change for android" FORCE)
    set(CMAKE_MAKE_PROGRAM "$ENV{ANDROID_NDK}/prebuilt/windows/bin/make.exe" CACHE STRING "" FORCE)
    set(ANDROID_NATIVE_API_LEVEL "16" CACHE STRING "" FORCE)
endif()
