set(enable-lgpl ON CACHE BOOL "" FORCE)
set(enable-octave-install OFF CACHE BOOL "" FORCE)
set(enable-png OFF CACHE BOOL "" FORCE)
set(enable-pthr-widget OFF CACHE BOOL "" FORCE)
set(enable-zlib OFF CACHE BOOL "" FORCE)
if (TOO_DEPLOY_TARGET STREQUAL "uwp" OR ANDROID)
    set(enable-opengl OFF CACHE BOOL "" FORCE)
endif ()
