set(enable-lgpl ON CACHE BOOL "")
set(enable-octave-install OFF CACHE BOOL "")
set(enable-png OFF CACHE BOOL "")
set(enable-pthr-widget OFF CACHE BOOL "")
set(enable-zlib OFF CACHE BOOL "")
if (DEPLOY_TARGET STREQUAL "uwp" OR ANDROID)
	set(enable-opengl OFF CACHE BOOL "")
endif ()
